baseurl: "/"
languageCode: "en-us"
title: "An Introduction to Data Science Methods in Education"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Syllabus
      url: "syllabus/"
      weight: 2
    - name: Schedule
      url: "schedule/"
      weight: 3
    - name: Homework and Readings
      url: "homework_readings/"
      weight: 4
    - name: Assignments
      url: "assignments/"
      weight: 5
    - name: Videos
      url: "videos/"
      weight: 6
    - name: Presentations
      url: "presentations/"
      weight: 7


params:
  description: "A website built through Hugo and blogdown."
  footer: ""

markup:
  goldmark:
    renderer:
      unsafe: true
