---
title: "Assignments"
author: "Alex Lishinski"
date: "8/19/2021"
output: html_document
---

## Homework (12-14)

Weekly homework. To be submitted in the form of an R Markdown file (`.Rmd`) via Canvas. There are a few weeks in which we may not have homework for different reasons; why the number of homeworks is listed as 12-14.

## Personal statement on data ethics

Write a personal statement on one’s perspective toward the role and nature of data, addressing how issues of equity, privacy, and ethics are central to data science in education (due approximately one-third of the way through the semester).

[Link to assignment details](assignment-data-ethics.html)

## Curating a data science resource

Curate a data science resource as a part of a class resource throughout the semester.

[Link to assignment details](assignment-curating-a-data-science-resource.html)

## Individual final project


Complete an individually-designed project that can take different forms (R Markdown Report, interactive Shiny app, interactive dashboard, etc.) related to identifying and solving a data-related problem in education using R (due approximately two-thirds of the way through the semester).

[Link to assignment details](assignment-final-project.html)
