---
title: "Syllabus"
author: "Alex Lishinski"
date: "8/18/2021"
output: html_document
---

# An Introduction to Data Science Methods in Education
*University of Tennessee, Knoxville*

Course Section: TPTE 595 (MA) and TPTE 695 (PhD) 
Meeting Time and Place: Thursday, 2:50 – 4:05 pm (online, partially synchronous) 
Course Credit Hours: 3
Course Website: https://f21-intro-to-data-sci-methods-in-ed.netlify.app/

## Faculty Contact Information
Dr. Alex Lishinski (they/them)
alishins@utk.edu
Zoom: https://tennessee.zoom.us/j/2299533064
Website: https://www.alexlishinski.com

Please don’t hesitate to email or contact me on Slack with updates, questions or concerns. I will try to respond within 24 hours during the week and 48 hours on the weekend. I will notify you if our response may be delayed. In short, please contact me.

## Course Description/Information:
Welcome to An Introduction to Data Science Methods in Education! The overarching goal of this course is to support graduate-level students across the Department of Theory and Practice in Teacher Education (and the Bailey Graduate School of Education) to be empowered to use new data sources and research methods in their research. 

## Value Proposition:  
Across education, several new courses and degree programs have been developed that share a focus on applying new research methods to new data sources, such as data from students’ interactions with digital technologies and teachers’ participation in online professional learning communities. Though these courses and programs have different names (e.g., learning analytics, educational data mining, and educational data science) that reflect different assumptions about education, they share a number of common features and can collectively be considered in terms of the application of data science methods in education (Wise, 2020), or data science in education.

The course will provide students with a foundation in data science in education, defined as those that integrate computation with statistics and substantive expertise. Also, the course will include opportunities for students to gain experience with specific data science techniques that may be widely used across research projects.

Students will have the opportunity to bring their own data from their research projects for use in this class. In this way, they will have immediate application for the concepts learned in the course. Bringing in one’s own data will be highly encouraged, as the work done in this class could serve as the foundation of a future conference proposal or publication for the student. If no data is immediately available from the student’s research, students can use one of hundreds of freely available datasets to complete coursework or students can use datasets provided to them.

Our goal in teaching this course will be to catalyze students’ interest in data science and to bolster their confidence in their abilities to use programming techniques to support their research programs. Many people who try to self-teach become overwhelmed by available resources. This course will provide scaffolding to help students become proficient in a few sophisticated data science techniques, and it will give students enough foundational knowledge to pick up new data science skills on their own after the course is through.
Student Learning Outcomes/Objectives:

The objectives for the proposed course are for students to be able to:

- Install, set up, and use R and RStudio
- Use reproducible workflows (so that analyses can easily be modified and then carried out again by the analyst or others) with R Markdown
- Prepare and explore complex data sources for analysis using the tidyverse suite of R packages
- Understand how issues of equity, privacy, and ethics are central to data science in education
- Develop a personal learning and development plan related to data science in education
- Develop a portfolio of work from this class that you can add to later
- Pursue an independent project to work toward a relevant professional goal

These objectives will serve as a foundation for later data science in education-related courses, including data visualization, creating interactive web applications, and machine learning applications.

# Learning Environment

This class will be taught in a fully-online format. We will use Zoom for synchronous (or at-the-same-time) a) introductions to new content, b) “try-it-out” laboratories, and c) discussions. We will also use a number of tools for asynchronous communication, including a) Slack, b) GitHub, and c) features of the Canvas course learning management system.

# Course Communications

## Slack
Slack is a communication platform designed for teams (e.g., in a company), that has begun to be used in education. We will use Slack to share resources and for asking and questions of one another. You are encouraged but not required to check Slack daily, and to use the app on your mobile device or phone. 

## Email
If you email me, you will generally receive a response within 24 hours. I ask for you to please try to respond within 24 hours, too. You can contact me via email (above) or Slack (preferred).

# How to Be Successful in This Course

Don’t hesitate to ask questions! Learning to do data science is challenging for everyone, and reaching out for support and assistance is imperative.
Our late assignment policy is that as long as you submit the assignment before I grade it, you will receive full credit. However, I may grade assignments very soon after they are due. For assignments received after the due date, 5% from the grade you otherwise would earn will be subtracted from your final grade for each day late.
Texts/Resources/Materials:

> Estrellado, R. A., Freer, E. A., Mostipak, J., Rosenberg, J. M., & Velásquez, I. C. (2020). Data science in education using R. London, England: Routledge. Freely-available from: http://www.datascienceineducation.com/

# Required Equipment
You will need a computer (Mac, Windows, or Linux are fine!) on which you can install applications, but you do not need a computer with any particular specifications (speed, storage, etc.) beyond what you use for other courses: whatever you have will work for this course.

# Major Assignments and Exams
- Complete homework each week 
- Four interactive examinations
- Write a personal statement on one’s perspective toward the role and nature of data, addressing how issues of equity, privacy, and ethics are central to data science in education (due approximately one-third of the way through the semester).
- Develop a personal learning and development plan related to data science in education 
- Complete an individually-designed project that can take different forms (R Markdown Report, interactive Shiny app, interactive dashboard, etc.) related to identifying and solving a data-related problem in education using R (due approximately two-thirds of the way through the semester).
- Develop a portfolio with your work from throughout the semester. 
- Complete an individually-designed project that can take different forms (R Markdown Report, interactive Shiny app, interactive dashboard, etc.) related to identifying and solving a data-related problem in education using R (due as a final exam at the end of the semester, with updates on progress made due throughout the semester).

# University Policies

## Academic Integrity:
“An essential feature of the University of Tennessee, Knoxville is a commitment to maintaining an atmosphere of intellectual integrity and academic honesty. As a student of the university, I pledge that I will neither knowingly give nor receive any inappropriate assistance in academic work, thus affirming my own personal commitment to honor and integrity.”

## University Civility Statement:
Civility is genuine respect and regard for others: politeness, consideration, tact, good manners, graciousness, cordiality, affability, amiability and courteousness. Civility enhances academic freedom and integrity, and is a prerequisite to the free exchange of ideas and knowledge in the learning community. Our community consists of students, faculty, staff, alumni, and campus visitors. Community members affect each other’s well-being and have a shared interest in creating and sustaining an environment where all community members and their points of view are valued and respected. Affirming the value of each member of the university community, the campus asks that all its members adhere to the principles of civility and community adopted by the campus: http://civility.utk.edu/.

## Disability Services:
“Any student who feels s/he may need an accommodation based on the impact of a disability should contact Student Disability Services in Dunford Hall, at 865-974-6087, or by video relay at, 865-622-6566, to coordinate reasonable academic accommodations.

## Your Role in Improving Teaching and Learning Through Course Assessment:
At UT, it is our collective responsibility to improve the state of teaching and learning. During the semester, you may be requested to assess aspects of this course either during class or at the completion of the class. You are encouraged to respond to these various forms of assessment as a means of continuing to improve the quality of the UT learning experience.

## Key Campus Resources for Students:
- Center for Career Development (Career counseling and resources; HIRE-A-VOL job search system)
- Course Catalogs  (Listing of academic programs, courses, and policies)
- Hilltopics (Campus and academic policies, procedures and standards of conduct)
- OIT HelpDesk (865) 974-9900
- Schedule of Classes/Timetable
- Student Health Center (visit the site for a list of services)
- Student Success Center (Academic support resources)
- Undergraduate Academic Advising (Advising resources, course requirements, and major guides)
- University Libraries (Access to library resources, databases, course reserves, and services)

The instructors reserve the right to revise, alter or amend this syllabus as necessary. Students will be notified in writing / email of any such changes. 
